/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = 
  {9, 9, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 1, 2};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {11, 1, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenthfiala_cost_y_e_hess:(i0[9],i1[0],i2[0],i3[8],i4[],i5[11])->(o0[9x9,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, *w1=w+1, w3, *w4=w+20, w5, w7, w8, w9;
  const casadi_real *cs, *wr2, *wr6;
  /* #0: @0 = zeros(9x9,1nz) */
  w0 = 0.;
  /* #1: @1 = zeros(9x1) */
  casadi_clear(w1, 9);
  /* #2: @2 = input[0][0] */
  wr2 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[2] */
  w3 = wr2[2];
  /* #4: @4 = input[5][1] */
  casadi_copy(arg[5] ? arg[5]+5 : 0, 6, w4);
  /* #5: @5 = @4[2] */
  for (rr=(&w5), cs=w4+2; cs!=w4+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  w3 -= w5;
  /* #7: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #8: @6 = input[3][0] */
  wr6 = arg[3] ? arg[3] : casadi_zeros;
  /* #9: {NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w7 = wr6[2];
  /* #10: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #11: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #12: @8 = (@8*@3) */
  w8 *= w3;
  /* #13: @9 = (@7*@3) */
  w9  = (w7*w3);
  /* #14: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #15: @8 = (@8+@9) */
  w8 += w9;
  /* #16: @9 = (@7*@5) */
  w9  = (w7*w5);
  /* #17: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #18: @9 = (-@9) */
  w9 = (- w9 );
  /* #19: @3 = (@3*@7) */
  w3 *= w7;
  /* #20: @3 = (@3*@5) */
  w3 *= w5;
  /* #21: @9 = (@9-@3) */
  w9 -= w3;
  /* #22: @8 = (@8+@9) */
  w8 += w9;
  /* #23: (@1[2] += @8) */
  for (rr=w1+2, cs=(&w8); rr!=w1+3; rr+=1) *rr += *cs++;
  /* #24: @8 = @1[2] */
  for (rr=(&w8), cs=w1+2; cs!=w1+3; cs+=1) *rr++ = *cs;
  /* #25: (@0[0] = @8) */
  for (rr=(&w0)+0, cs=(&w8); rr!=(&w0)+1; rr+=1) *rr = *cs++;
  /* #26: @8 = @0' */
  casadi_trans((&w0),casadi_s0, (&w8), casadi_s0, iw);
  /* #27: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 10;
  if (sz_w) *sz_w = 38;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 10*sizeof(casadi_int);
  if (sz_w) *sz_w = 38*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
