/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {11, 1, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[19] = 
  {9, 8, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 0, 1, 2, 3, 4,
  5, 7, 8};
static const casadi_int casadi_s6[3] = {8, 0, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenthfiala_cost_y_e_fun_jac_ut_xt:(i0[9],i1[0],i2[0],i3[],i4[11])->(o0[8],o1[9x8,8nz],o2[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w1, *w2=w+10, w3, *w4=w+17, *w5=w+25;
  const casadi_real *cs, *wr0;
  /* #0: @0 = input[0][0] */
  wr0 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[0] */
  w1 = wr0[0];
  /* #2: @2 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+5 : 0, 6, w2);
  /* #3: @3 = @2[0] */
  for (rr=(&w3), cs=w2+0; cs!=w2+1; cs+=1) *rr++ = *cs;
  /* #4: @1 = (@1-@3) */
  w1 -= w3;
  /* #5: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #6: @1 = @0[1] */
  w1 = wr0[1];
  /* #7: @3 = @2[1] */
  for (rr=(&w3), cs=w2+1; cs!=w2+2; cs+=1) *rr++ = *cs;
  /* #8: @1 = (@1-@3) */
  w1 -= w3;
  /* #9: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #10: @1 = @0[2] */
  w1 = wr0[2];
  /* #11: @3 = @2[2] */
  for (rr=(&w3), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #12: @1 = (@1-@3) */
  w1 -= w3;
  /* #13: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #14: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #15: @3 = atan2(@3,@1) */
  w3  = atan2(w3,w1);
  /* #16: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #17: @3 = @0[3] */
  w3 = wr0[3];
  /* #18: @1 = @2[3] */
  for (rr=(&w1), cs=w2+3; cs!=w2+4; cs+=1) *rr++ = *cs;
  /* #19: @3 = (@3-@1) */
  w3 -= w1;
  /* #20: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #21: @3 = @0[4] */
  w3 = wr0[4];
  /* #22: @1 = @2[4] */
  for (rr=(&w1), cs=w2+4; cs!=w2+5; cs+=1) *rr++ = *cs;
  /* #23: @3 = (@3-@1) */
  w3 -= w1;
  /* #24: output[0][4] = @3 */
  if (res[0]) res[0][4] = w3;
  /* #25: @3 = @0[5] */
  w3 = wr0[5];
  /* #26: @1 = @2[5] */
  for (rr=(&w1), cs=w2+5; cs!=w2+6; cs+=1) *rr++ = *cs;
  /* #27: @3 = (@3-@1) */
  w3 -= w1;
  /* #28: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #29: @3 = @0[7] */
  w3 = wr0[7];
  /* #30: output[0][6] = @3 */
  if (res[0]) res[0][6] = w3;
  /* #31: @3 = @0[8] */
  w3 = wr0[8];
  /* #32: output[0][7] = @3 */
  if (res[0]) res[0][7] = w3;
  /* #33: @4 = zeros(9x8,8nz) */
  casadi_clear(w4, 8);
  /* #34: @5 = ones(8x1) */
  casadi_fill(w5, 8, 1.);
  /* #35: (@4[:8] = @5) */
  for (rr=w4+0, cs=w5; rr!=w4+8; rr+=1) *rr = *cs++;
  /* #36: output[1][0] = @4 */
  casadi_copy(w4, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 33;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 33*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
