/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_cost_y_0_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = 
  {11, 11, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 1, 1, 1, 4};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {2, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {10, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {11, 1, 1};

static const casadi_real casadi_zeros[10] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0.};

/* f1tenthfiala_cost_y_0_hess:(i0[9],i1[2],i2[0],i3[10],i4[],i5[11])->(o0[11x11,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, *w02=w+10, w03, *w04=w+20, w05, w07, w08, *w09=w+39, w10, w11;
  const casadi_real *cs, *wr02, *wr06;
  /* #0: @0 = zeros(11x11,1nz) */
  w00 = 0.;
  /* #1: @1 = zeros(9x1) */
  casadi_clear(w01, 9);
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[2] */
  w03 = wr02[2];
  /* #4: @4 = input[5][1] */
  casadi_copy(arg[5] ? arg[5]+5 : 0, 6, w04);
  /* #5: @5 = @4[2] */
  for (rr=(&w05), cs=w04+2; cs!=w04+3; cs+=1) *rr++ = *cs;
  /* #6: @3 = (@3-@5) */
  w03 -= w05;
  /* #7: @5 = sin(@3) */
  w05 = sin( w03 );
  /* #8: @6 = input[3][0] */
  wr06 = arg[3] ? arg[3] : casadi_zeros;
  /* #9: {NULL, NULL, @7, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w07 = wr06[2];
  /* #10: @8 = (@5*@7) */
  w08  = (w05*w07);
  /* #11: @3 = cos(@3) */
  w03 = cos( w03 );
  /* #12: @9 = ones(11x1) */
  casadi_fill(w09, 11, 1.);
  /* #13: {NULL, @2} = vertsplit(@9) */
  casadi_copy(w09+2, 9, w02);
  /* #14: @10 = @2[2] */
  for (rr=(&w10), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #15: @11 = (@3*@10) */
  w11  = (w03*w10);
  /* #16: @8 = (@8*@11) */
  w08 *= w11;
  /* #17: @11 = (@7*@11) */
  w11  = (w07*w11);
  /* #18: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #19: @8 = (@8+@11) */
  w08 += w11;
  /* #20: @5 = (@5*@10) */
  w05 *= w10;
  /* #21: @10 = (@7*@5) */
  w10  = (w07*w05);
  /* #22: @10 = (@3*@10) */
  w10  = (w03*w10);
  /* #23: @10 = (-@10) */
  w10 = (- w10 );
  /* #24: @3 = (@3*@7) */
  w03 *= w07;
  /* #25: @3 = (@3*@5) */
  w03 *= w05;
  /* #26: @10 = (@10-@3) */
  w10 -= w03;
  /* #27: @8 = (@8+@10) */
  w08 += w10;
  /* #28: (@1[2] += @8) */
  for (rr=w01+2, cs=(&w08); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #29: @8 = @1[2] */
  for (rr=(&w08), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #30: (@0[0] = @8) */
  for (rr=(&w00)+0, cs=(&w08); rr!=(&w00)+1; rr+=1) *rr = *cs++;
  /* #31: @8 = @0' */
  casadi_trans((&w00),casadi_s0, (&w08), casadi_s0, iw);
  /* #32: output[0][0] = @8 */
  if (res[0]) res[0][0] = w08;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_0_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_0_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_cost_y_0_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_0_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_0_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_0_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_0_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 52;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 12*sizeof(casadi_int);
  if (sz_w) *sz_w = 52*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
