/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {11, 1, 1};
static const casadi_int casadi_s5[3] = {10, 1, 1};
static const casadi_int casadi_s6[23] = 
  {11, 10, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 2, 3, 4,
  5, 6, 7, 9, 10, 0, 1};
static const casadi_int casadi_s7[3] = {10, 0, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenthfiala_cost_y_0_fun_jac_ut_xt:(i0[9],i1[2],i2[0],i3[],i4[11])->(o0[10],o1[11x10,10nz],o2[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, *w02=w+10, w03, w04, w05, *w06=w+19, *w07=w+21, *w08=w+31, w09, w10;
  casadi_real w11, w12, *w13=w+46;
  const casadi_real *cs, *wr00;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[0] */
  w01 = wr00[0];
  /* #2: @2 = input[4][1] */
  casadi_copy(arg[4] ? arg[4]+5 : 0, 6, w02);
  /* #3: @3 = @2[0] */
  for (rr=(&w03), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #6: @1 = @0[1] */
  w01 = wr00[1];
  /* #7: @3 = @2[1] */
  for (rr=(&w03), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #8: @1 = (@1-@3) */
  w01 -= w03;
  /* #9: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #10: @1 = @0[2] */
  w01 = wr00[2];
  /* #11: @3 = @2[2] */
  for (rr=(&w03), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #12: @1 = (@1-@3) */
  w01 -= w03;
  /* #13: @3 = sin(@1) */
  w03 = sin( w01 );
  /* #14: @1 = cos(@1) */
  w01 = cos( w01 );
  /* #15: @4 = atan2(@3,@1) */
  w04  = atan2(w03,w01);
  /* #16: output[0][2] = @4 */
  if (res[0]) res[0][2] = w04;
  /* #17: @4 = @0[3] */
  w04 = wr00[3];
  /* #18: @5 = @2[3] */
  for (rr=(&w05), cs=w02+3; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #19: @4 = (@4-@5) */
  w04 -= w05;
  /* #20: output[0][3] = @4 */
  if (res[0]) res[0][3] = w04;
  /* #21: @4 = @0[4] */
  w04 = wr00[4];
  /* #22: @5 = @2[4] */
  for (rr=(&w05), cs=w02+4; cs!=w02+5; cs+=1) *rr++ = *cs;
  /* #23: @4 = (@4-@5) */
  w04 -= w05;
  /* #24: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #25: @4 = @0[5] */
  w04 = wr00[5];
  /* #26: @5 = @2[5] */
  for (rr=(&w05), cs=w02+5; cs!=w02+6; cs+=1) *rr++ = *cs;
  /* #27: @4 = (@4-@5) */
  w04 -= w05;
  /* #28: output[0][5] = @4 */
  if (res[0]) res[0][5] = w04;
  /* #29: @4 = @0[7] */
  w04 = wr00[7];
  /* #30: output[0][6] = @4 */
  if (res[0]) res[0][6] = w04;
  /* #31: @4 = @0[8] */
  w04 = wr00[8];
  /* #32: output[0][7] = @4 */
  if (res[0]) res[0][7] = w04;
  /* #33: @6 = input[1][0] */
  casadi_copy(arg[1], 2, w06);
  /* #34: output[0][8] = @6 */
  if (res[0]) casadi_copy(w06, 2, res[0]+8);
  /* #35: @7 = zeros(11x10,10nz) */
  casadi_clear(w07, 10);
  /* #36: @8 = ones(11x1) */
  casadi_fill(w08, 11, 1.);
  /* #37: {@6, @0} = vertsplit(@8) */
  casadi_copy(w08, 2, w06);
  casadi_copy(w08+2, 9, w00);
  /* #38: @4 = @0[0] */
  for (rr=(&w04), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #39: @5 = @0[1] */
  for (rr=(&w05), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #40: @9 = @0[2] */
  for (rr=(&w09), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #41: @10 = (@1*@9) */
  w10  = (w01*w09);
  /* #42: @1 = (@1*@10) */
  w01 *= w10;
  /* #43: @9 = (@3*@9) */
  w09  = (w03*w09);
  /* #44: @3 = (@3*@9) */
  w03 *= w09;
  /* #45: @1 = (@1+@3) */
  w01 += w03;
  /* #46: @3 = @0[3] */
  for (rr=(&w03), cs=w00+3; cs!=w00+4; cs+=1) *rr++ = *cs;
  /* #47: @9 = @0[4] */
  for (rr=(&w09), cs=w00+4; cs!=w00+5; cs+=1) *rr++ = *cs;
  /* #48: @10 = @0[5] */
  for (rr=(&w10), cs=w00+5; cs!=w00+6; cs+=1) *rr++ = *cs;
  /* #49: @11 = @0[7] */
  for (rr=(&w11), cs=w00+7; cs!=w00+8; cs+=1) *rr++ = *cs;
  /* #50: @12 = @0[8] */
  for (rr=(&w12), cs=w00+8; cs!=w00+9; cs+=1) *rr++ = *cs;
  /* #51: @13 = vertcat(@4, @5, @1, @3, @9, @10, @11, @12, @6) */
  rr=w13;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w01;
  *rr++ = w03;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  for (i=0, cs=w06; i<2; ++i) *rr++ = *cs++;
  /* #52: (@7[:10] = @13) */
  for (rr=w07+0, cs=w13; rr!=w07+10; rr+=1) *rr = *cs++;
  /* #53: output[1][0] = @7 */
  casadi_copy(w07, 10, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 56;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 56*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
