"""Generates mb_jax.py: a JAX twin of mb_fiala.vehicle_dynamics_mb_fiala (the fork's multi-body model with the
per-corner Fiala tire), for the nominal GPU sim of the sim stage (batched rollouts, autodiff Jacobians). Mechanical
transformation of the generated numba source:
  - the DYNAMIC branch only (|vx| >= 0.5 m/s: the kinematic low-speed switch is dropped; every run here starts and
    stays above it -- a lane below 0.3 m/s fails),
  - steering_constraint replicated with jnp.where, the gym's accel input fixed at 0 (the driveline torques are
    added outside, as in mb_car), negative-wheel-spin guards as jnp.maximum / jnp.where,
  - np -> jnp, the state derivative built as a list and stacked.
check_mb_jax.py compares it with the numba version.   python make_mb_jax.py"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, 'mb_fiala.py')).read()
start = src.index('@njit(cache=True)\ndef vehicle_dynamics_mb_fiala(')
fn = src[start:].replace('@njit(cache=True)\n', '', 1)
fn = fn.replace('def vehicle_dynamics_mb_fiala(x: np.ndarray, u_init: np.ndarray, params: np.ndarray, fiala: np.ndarray) -> np.ndarray:',
                'def vehicle_dynamics_mb_jax(x, u_init, params, fiala):')
fn = fn.replace('u = np.zeros_like(u_init)', 'u = [0.0, 0.0]')
fn = fn.replace('u[0] = steering_constraint(', 'u[0] = _steer_c(')
fn = fn.replace('u[1] = accl_constraints(', 'u[1] = _zero_accel(')
fn = re.sub(r'if (u_w_\w+) < 0\.0:\n\s+\1 \*= 0', r'\1 = jnp.maximum(\1, 0.0)', fn)
fn = fn.replace('f = np.zeros(29)  # init \'right hand side\'', 'f = [0.0] * 29')
fn = re.sub(r"    if u\[1\] > 0:\n        T_B = 0\.0\n        T_E = m \* R_w \* u\[1\]\n    else:\n        T_B = m \* R_w \* u\[1\]\n        T_E = 0\.0",
            '    T_B = 0.0\n    T_E = 0.0', fn)
fn = fn.replace("""    for iState in range(23, 27):
        if x[iState] < 0.0:
            x[iState] = 0.0
            f[iState] = 0.0""", """    for iState in range(23, 27):
        f[iState] = jnp.where(x[iState] < 0.0, 0.0, f[iState])""")
fn = re.sub(r'\n    return f\s*$', '\n    return jnp.stack(f)\n', fn)

# keep only the else-branch of every `if abs(x[3]) < KIN_THRESH:` (dynamic model)
out, lines, i = [], fn.split('\n'), 0
while i < len(lines):
    ln = lines[i]
    if ln.strip() == 'if abs(x[3]) < KIN_THRESH:':
        ind = len(ln) - len(ln.lstrip())
        i += 1
        while not (lines[i].strip() == 'else:' and len(lines[i]) - len(lines[i].lstrip()) == ind):
            i += 1
        i += 1
        while i < len(lines) and (lines[i].strip() == '' or len(lines[i]) - len(lines[i].lstrip()) > ind):
            out.append(lines[i][4:] if lines[i].strip() else lines[i])
            i += 1
        continue
    out.append(ln)
    i += 1
fn = '\n'.join(out)
fn = re.sub(r'\bnp\.', 'jnp.', fn)
assert 'KIN_THRESH:' not in fn and 'steering_constraint' not in fn and 'np.zeros' not in fn

head = '''"""GENERATED by make_mb_jax.py from mb_fiala.py (the f1tenth_gym fork's multi_body.py with LLA-MPC's Fiala tire):
the JAX twin of vehicle_dynamics_mb_fiala, dynamic branch only. Do not edit; regenerate."""
import jax.numpy as jnp


def _fiala(kappa, alpha_mb, F_z, C, mu):
    ta = jnp.tan(-alpha_mb)
    sig = jnp.sqrt(ta * ta + kappa * kappa + 1e-2)
    Fmax = mu * jnp.maximum(F_z, 0.0)
    Fs = jnp.maximum(Fmax, 1e-9)
    Cs = C * sig
    brush = Cs - Cs * Cs / (3.0 * Fs) + Cs * Cs * Cs / (27.0 * Fs * Fs)
    Ft = jnp.where(sig < 3.0 * Fs / C, brush, Fmax)
    Ft = jnp.where(Fmax <= 1e-9, 0.0, Ft)
    return Ft * kappa / sig, Ft * ta / sig


def _steer_c(steering_angle, steering_velocity, s_min, s_max, sv_min, sv_max):
    """f1tenth_gym utils.steering_constraint."""
    stop = ((steering_angle <= s_min) & (steering_velocity <= 0)) | ((steering_angle >= s_max) & (steering_velocity >= 0))
    return jnp.where(stop, 0.0, jnp.clip(steering_velocity, sv_min, sv_max))


def _zero_accel(*args):
    return 0.0


'''
open(os.path.join(HERE, 'mb_jax.py'), 'w').write(head + fn)
print('wrote mb_jax.py')
