"""Generates mb_fiala.py: the f1tenth_gym fork's vehicle_dynamics_mb (multi_body.py, verbatim) with its Pacejka tire
block replaced by LLA-MPC's Fiala/brush combined-slip tire on each corner (per-tire stiffness, peak mu Fz from that
wheel's own suspension load, force along the combined slip vector, the 1e-2 slip regularizer of
nmpc_gen_fiala_fixed). The fork is not modified.   python make_mb_fiala.py"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', 'f1tenth_gym', 'f1tenth_gym', 'envs', 'dynamic_models', 'multi_body', 'multi_body.py')
s = open(SRC).read()
start = s.index('def vehicle_dynamics_mb(')
end = s.index('@njit(cache=True)\ndef get_standardized_state_mb')
fn = '@njit(cache=True)\n' + s[start:end]
fn = fn.replace('def vehicle_dynamics_mb(x: np.ndarray, u_init: np.ndarray, params: np.ndarray) -> np.ndarray:',
                'def vehicle_dynamics_mb_fiala(x: np.ndarray, u_init: np.ndarray, params: np.ndarray, fiala: np.ndarray) -> np.ndarray:')
a = fn.index('    # compute longitudinal tire forces using the magic formula for pure slip')
b = fn.index('    # auxiliary movements for compliant joint equations')
tire = '''    # tire forces: LLA-MPC's Fiala / brush combined slip per corner (replaces the Pacejka block); MB conventions:
    # longitudinal slip s = 1 - R_w w / u (kappa = -s), alpha = atan(lateral / longitudinal) - delta (standard
    # slip angle = -alpha); F_y > 0 for a positive standard slip angle, as the MB force balance expects
    F_x_LF, F_y_LF = _fiala(-s_lf, alpha_LF, F_z_LF, fiala[0], fiala[2])
    F_x_RF, F_y_RF = _fiala(-s_rf, alpha_RF, F_z_RF, fiala[0], fiala[2])
    F_x_LR, F_y_LR = _fiala(-s_lr, alpha_LR, F_z_LR, fiala[1], fiala[2])
    F_x_RR, F_y_RR = _fiala(-s_rr, alpha_RR, F_z_RR, fiala[1], fiala[2])

'''
fn = fn[:a] + tire + fn[b:]
head = '''"""GENERATED by make_mb_fiala.py from the f1tenth_gym fork's multi_body.py (s-hliao/f1tenth_gym, dev-humble):
vehicle_dynamics_mb with LLA-MPC's Fiala combined-slip tire per corner. Do not edit; regenerate."""
import numpy as np
from numba import njit

from f1tenth_gym.envs.dynamic_models.utils import steering_constraint, accl_constraints
from f1tenth_gym.envs.dynamic_models.kinematic import vehicle_dynamics_ks_cog


@njit(cache=True)
def _fiala(kappa, alpha_mb, F_z, C, mu):
    ta = np.tan(-alpha_mb)
    sig = np.sqrt(ta * ta + kappa * kappa + 1e-2)
    Fmax = mu * max(F_z, 0.0)
    if Fmax <= 1e-9:
        return 0.0, 0.0
    if sig < 3.0 * Fmax / C:
        Cs = C * sig
        Ft = Cs - Cs * Cs / (3.0 * Fmax) + Cs * Cs * Cs / (27.0 * Fmax * Fmax)
    else:
        Ft = Fmax
    return Ft * kappa / sig, Ft * ta / sig


'''
open(os.path.join(HERE, 'mb_fiala.py'), 'w').write(head + fn)
print('wrote mb_fiala.py', len(fn.splitlines()), 'lines')
