"""GENERATED by make_mb_jax.py from mb_fiala.py (the f1tenth_gym fork's multi_body.py with LLA-MPC's Fiala tire):
the JAX twin of vehicle_dynamics_mb_fiala, dynamic branch only. Do not edit; regenerate."""
import jax.numpy as jnp


def _fiala(kappa, alpha_mb, F_z, C, mu):
    ta = jnp.tan(-alpha_mb)
    sig = jnp.sqrt(ta * ta + kappa * kappa + 1e-2)
    Fmax = mu * jnp.maximum(F_z, 0.0)
    Fs = jnp.maximum(Fmax, 1e-9)
    Cs = C * sig
    brush = Cs - Cs * Cs / (3.0 * Fs) + Cs * Cs * Cs / (27.0 * Fs * Fs)
    Ft = jnp.where(sig < 3.0 * Fs / C, brush, Fmax)
    Ft = jnp.where(Fmax <= 1e-9, 0.0, Ft)
    return Ft * kappa / sig, Ft * ta / sig


def _steer_c(steering_angle, steering_velocity, s_min, s_max, sv_min, sv_max):
    """f1tenth_gym utils.steering_constraint."""
    stop = ((steering_angle <= s_min) & (steering_velocity <= 0)) | ((steering_angle >= s_max) & (steering_velocity >= 0))
    return jnp.where(stop, 0.0, jnp.clip(steering_velocity, sv_min, sv_max))


def _zero_accel(*args):
    return 0.0


def vehicle_dynamics_mb_jax(x, u_init, params, fiala):
    """
    vehicleDynamics_mb - multi-body vehicle dynamics based on the DoT (department of transportation) vehicle dynamics
    reference point: center of mass

    Syntax:
        f = vehicleDynamics_mb(x,u,p)

    Inputs:
        :param x: vehicle state vector
        :param uInit: vehicle input vector
        :param params: vehicle parameter vector

    Outputs:
        :return f: right-hand side of differential equations
    """

    # ------------- BEGIN CODE --------------

    # set gravity constant
    g = 9.81  # [m/s^2]

    # states
    # x0 = x-position in a global coordinate system
    # x1 = y-position in a global coordinate system
    # x2 = steering angle of front wheels
    # x3 = velocity in x-direction
    # x4 = yaw angle
    # x5 = yaw rate

    # x6 = roll angle
    # x7 = roll rate
    # x8 = pitch angle
    # x9 = pitch rate
    # x10 = velocity in y-direction
    # x11 = z-position
    # x12 = velocity in z-direction

    # x13 = roll angle front
    # x14 = roll rate front
    # x15 = velocity in y-direction front
    # x16 = z-position front
    # x17 = velocity in z-direction front

    # x18 = roll angle rear
    # x19 = roll rate rear
    # x20 = velocity in y-direction rear
    # x21 = z-position rear
    # x22 = velocity in z-direction rear

    # x23 = left front wheel angular speed
    # x24 = right front wheel angular speed
    # x25 = left rear wheel angular speed
    # x26 = right rear wheel angular speed

    # x27 = delta_y_f
    # x28 = delta_y_r

    # u0 = steering angle velocity of front wheels
    # u1 = acceleration

    u = [0.0, 0.0]

    mu = params[0]  # lateral friction coefficient
    C_Sf = params[1]  # front tire cornering stiffness [N/rad]
    C_Sr = params[2]  # rear tire cornering stiffness [N/rad]
    lf = params[3]  # distance from CoG to front axle [m]
    lr = params[4]  # distance from CoG to rear axle [m]
    h = params[5]  # CoG height of total mass above ground [m]
    m = params[6]  # total vehicle mass [kg]
    I = params[7]  # moment of inertia in yaw [kg m^2]

    # Steering constraints
    s_min = params[8]   # minimum steering angle [rad]
    s_max = params[9]   # maximum steering angle [rad]
    sv_min = params[10]  # minimum steering velocity [rad/s]
    sv_max = params[11]  # maximum steering velocity [rad/s]

    # Longitudinal constraints
    v_switch = params[12]  # switching velocity [m/s]
    a_max = params[13]  # maximum absolute acceleration [m/s^2]
    v_min = params[14]  # minimum velocity [m/s]
    v_max = params[15]  # maximum velocity [m/s]

    # Vehicle geometry
    width = params[16]  # vehicle width [m]
    length = params[17]  # vehicle length [m]

    # Curvature and jerk constraints
    kappa_dot_max = params[18]  # max curvature rate [1/s]
    kappa_dot_dot_max = params[19]  # max curvature acceleration [1/s^2]
    j_max = params[20]  # max longitudinal jerk [m/s^3]
    j_dot_max = params[21]  # max change in jerk [m/s^4]

    # Mass breakdown
    m_s = params[22]  # sprung mass [kg]
    m_uf = params[23]  # front unsprung mass [kg]
    m_ur = params[24]  # rear unsprung mass [kg]

    # Sprung mass inertia
    I_Phi_s = params[25]  # roll inertia of sprung mass [kg m^2]
    I_y_s = params[26]  # pitch inertia of sprung mass [kg m^2]
    I_z = params[27]  # yaw inertia of sprung mass [kg m^2]
    I_xz_s = params[28]  # cross-product inertia [kg m^2]

    # Suspension spring/damping
    K_sf = params[29]  # front suspension spring rate [N/m]
    K_sdf = params[30]  # front suspension damping [N·s/m]
    K_sr = params[31]  # rear suspension spring rate [N/m]
    K_sdr = params[32]  # rear suspension damping [N·s/m]

    # Track widths and compliant joints
    T_f = params[33]  # front track width [m]
    T_r = params[34]  # rear track width [m]
    K_ras = params[35]  # lateral spring rate at pin joint [N/m]
    K_tsf = params[36]  # front torsion roll stiffness [N·m/rad]
    K_tsr = params[37]  # rear torsion roll stiffness [N·m/rad]
    K_rad = params[38]  # damping rate at pin joint [N·s/m]
    K_zt = params[39]  # vertical tire spring rate [N/m]

    # CoG and roll axis heights
    h_cg = params[40]  # center of gravity height of total mass [m]
    h_raf = params[41]  # roll axis front height [m]
    h_rar = params[42]  # roll axis rear height [m]
    h_s = params[43]  # sprung mass CoG height [m]

    # Unsprung mass inertias
    I_uf = params[44]  # front unsprung inertia [kg m^2]
    I_ur = params[45]  # rear unsprung inertia [kg m^2]

    # Wheel and compliance
    I_y_w = params[46]  # wheel rotational inertia [kg m^2]
    K_lt = params[47]  # lateral compliance rate [m/N]
    R_w = params[48]  # wheel/tire effective radius [m]

    # Torque splits
    T_sb = params[49]  # brake torque split
    T_se = params[50]  # engine torque split

    # Suspension toe parameters
    D_f = params[51]  # front toe compliance [rad/m]
    D_r = params[52]  # rear toe compliance [rad/m]
    E_f = params[53]  # front compliance nonlinearity
    E_r = params[54]  # rear compliance nonlinearity

    KIN_THRESH = 0.5

    # consider steering and acceleration constraints - outside of the integration
    u[0] = _steer_c(
        x[2],
        u_init[0],
        s_min,
        s_max,
        sv_min,
        sv_max,
    )
    u[1] = _zero_accel(
        x[3],
        u_init[1],
        v_switch,
        a_max,
        v_min,
        v_max,
    )

    beta = jnp.arctan(x[10] / x[3])
    vel = jnp.sqrt(x[3] ** 2 + x[10] ** 2)

    # vertical tire forces
    F_z_LF = (
        x[16]
        + R_w * (jnp.cos(x[13]) - 1)
        - 0.5 * T_f * jnp.sin(x[13])
    ) * K_zt
    F_z_RF = (
        x[16]
        + R_w * (jnp.cos(x[13]) - 1)
        + 0.5 * T_f * jnp.sin(x[13])
    ) * K_zt
    F_z_LR = (
        x[21]
        + R_w * (jnp.cos(x[18]) - 1)
        - 0.5 * T_r * jnp.sin(x[18])
    ) * K_zt
    F_z_RR = (
        x[21]
        + R_w * (jnp.cos(x[18]) - 1)
        + 0.5 * T_r * jnp.sin(x[18])
    ) * K_zt

    # obtain individual tire speeds
    u_w_lf = (x[3] + 0.5 * T_f * x[5]) * jnp.cos(x[2]) + (
        x[10] + lf * x[5]
    ) * jnp.sin(x[2])
    u_w_rf = (x[3] - 0.5 * T_f * x[5]) * jnp.cos(x[2]) + (
        x[10] + lf * x[5]
    ) * jnp.sin(x[2])
    u_w_lr = x[3] + 0.5 * T_r * x[5]
    u_w_rr = x[3] - 0.5 * T_r * x[5]

    # negative wheel spin forbidden
    u_w_lf = jnp.maximum(u_w_lf, 0.0)

    u_w_rf = jnp.maximum(u_w_rf, 0.0)

    u_w_lr = jnp.maximum(u_w_lr, 0.0)

    u_w_rr = jnp.maximum(u_w_rr, 0.0)
    # compute longitudinal slip
    # switch to kinematic model for small velocities
    s_lf = 1 - R_w * x[23] / u_w_lf
    s_rf = 1 - R_w * x[24] / u_w_rf
    s_lr = 1 - R_w * x[25] / u_w_lr
    s_rr = 1 - R_w * x[26] / u_w_rr

    # lateral slip angles
    # switch to kinematic model for small velocities
    alpha_LF = (
        jnp.arctan(
            (x[10] + lf * x[5] - x[14] * (R_w - x[16]))
            / (x[3] + 0.5 * T_f * x[5])
        )
        - x[2]
    )
    alpha_RF = (
        jnp.arctan(
            (x[10] + lf * x[5] - x[14] * (R_w - x[16]))
            / (x[3] - 0.5 * T_f * x[5])
        )
        - x[2]
    )
    alpha_LR = jnp.arctan(
        (x[10] - lr * x[5] - x[19] * (R_w - x[21]))
        / (x[3] + 0.5 * T_r * x[5])
    )
    alpha_RR = jnp.arctan(
        (x[10] - lr * x[5] - x[19] * (R_w - x[21]))
        / (x[3] - 0.5 * T_r * x[5])
    )

    # auxiliary suspension movement
    z_SLF = (
        (h_s - R_w + x[16] - x[11]) / jnp.cos(x[6])
        - h_s
        + R_w
        + lf * x[8]
        + 0.5 * (x[6] - x[13]) * T_f
    )
    z_SRF = (
        (h_s - R_w + x[16] - x[11]) / jnp.cos(x[6])
        - h_s
        + R_w
        + lf * x[8]
        - 0.5 * (x[6] - x[13]) * T_f
    )
    z_SLR = (
        (h_s - R_w + x[21] - x[11]) / jnp.cos(x[6])
        - h_s
        + R_w
        - lr * x[8]
        + 0.5 * (x[6] - x[18]) * T_r
    )
    z_SRR = (
        (h_s - R_w + x[21] - x[11]) / jnp.cos(x[6])
        - h_s
        + R_w
        - lr * x[8]
        - 0.5 * (x[6] - x[18]) * T_r
    )

    dz_SLF = x[17] - x[12] + lf * x[9] + 0.5 * (x[7] - x[14]) * T_f
    dz_SRF = x[17] - x[12] + lf * x[9] - 0.5 * (x[7] - x[14]) * T_f
    dz_SLR = x[22] - x[12] - lr * x[9] + 0.5 * (x[7] - x[19]) * T_r
    dz_SRR = x[22] - x[12] - lr * x[9] - 0.5 * (x[7] - x[19]) * T_r

    # camber angles
    gamma_LF = x[6] + D_f * z_SLF + E_f * (z_SLF) ** 2
    gamma_RF = x[6] - D_f * z_SRF - E_f * (z_SRF) ** 2
    gamma_LR = x[6] + D_r * z_SLR + E_r * (z_SLR) ** 2
    gamma_RR = x[6] - D_r * z_SRR - E_r * (z_SRR) ** 2

    # tire forces: LLA-MPC's Fiala / brush combined slip per corner (replaces the Pacejka block); MB conventions:
    # longitudinal slip s = 1 - R_w w / u (kappa = -s), alpha = atan(lateral / longitudinal) - delta (standard
    # slip angle = -alpha); F_y > 0 for a positive standard slip angle, as the MB force balance expects
    F_x_LF, F_y_LF = _fiala(-s_lf, alpha_LF, F_z_LF, fiala[0], fiala[2])
    F_x_RF, F_y_RF = _fiala(-s_rf, alpha_RF, F_z_RF, fiala[0], fiala[2])
    F_x_LR, F_y_LR = _fiala(-s_lr, alpha_LR, F_z_LR, fiala[1], fiala[2])
    F_x_RR, F_y_RR = _fiala(-s_rr, alpha_RR, F_z_RR, fiala[1], fiala[2])

    # auxiliary movements for compliant joint equations
    delta_z_f = h_s - R_w + x[16] - x[11]
    delta_z_r = h_s - R_w + x[21] - x[11]

    delta_phi_f = x[6] - x[13]
    delta_phi_r = x[6] - x[18]

    dot_delta_phi_f = x[7] - x[14]
    dot_delta_phi_r = x[7] - x[19]

    dot_delta_z_f = x[17] - x[12]
    dot_delta_z_r = x[22] - x[12]

    dot_delta_y_f = x[10] + lf * x[5] - x[15]
    dot_delta_y_r = x[10] - lr * x[5] - x[20]

    delta_f = (
        delta_z_f * jnp.sin(x[6])
        - x[27] * jnp.cos(x[6])
        - (h_raf - R_w) * jnp.sin(delta_phi_f)
    )
    delta_r = (
        delta_z_r * jnp.sin(x[6])
        - x[28] * jnp.cos(x[6])
        - (h_rar - R_w) * jnp.sin(delta_phi_r)
    )

    dot_delta_f = (
        (delta_z_f * jnp.cos(x[6]) + x[27] * jnp.sin(x[6])) * x[7]
        + dot_delta_z_f * jnp.sin(x[6])
        - dot_delta_y_f * jnp.cos(x[6])
        - (h_raf - R_w) * jnp.cos(delta_phi_f) * dot_delta_phi_f
    )
    dot_delta_r = (
        (delta_z_r * jnp.cos(x[6]) + x[28] * jnp.sin(x[6])) * x[7]
        + dot_delta_z_r * jnp.sin(x[6])
        - dot_delta_y_r * jnp.cos(x[6])
        - (h_rar - R_w) * jnp.cos(delta_phi_r) * dot_delta_phi_r
    )

    # compliant joint forces
    F_RAF = delta_f * K_ras + dot_delta_f * K_rad
    F_RAR = delta_r * K_ras + dot_delta_r * K_rad

    # auxiliary suspension forces (bump stop neglected  squat/lift forces neglected)
    F_SLF = (
        m_s * g * lr / (2 * (lf + lr))
        - z_SLF * K_sf
        - dz_SLF * K_sdf
        + (x[6] - x[13]) * K_tsf / T_f
    )

    F_SRF = (
        m_s * g * lr / (2 * (lf + lr))
        - z_SRF * K_sf
        - dz_SRF * K_sdf
        - (x[6] - x[13]) * K_tsf / T_f
    )

    F_SLR = (
        m_s * g * lf / (2 * (lf + lr))
        - z_SLR * K_sr
        - dz_SLR * K_sdr
        + (x[6] - x[18]) * K_tsr / T_r
    )

    F_SRR = (
        m_s * g * lf / (2 * (lf + lr))
        - z_SRR * K_sr
        - dz_SRR * K_sdr
        - (x[6] - x[18]) * K_tsr / T_r
    )

    # auxiliary variables sprung mass
    sumX = (
        F_x_LR
        + F_x_RR
        + (F_x_LF + F_x_RF) * jnp.cos(x[2])
        - (F_y_LF + F_y_RF) * jnp.sin(x[2])
    )

    sumN = (
        (F_y_LF + F_y_RF) * lf * jnp.cos(x[2])
        + (F_x_LF + F_x_RF) * lf * jnp.sin(x[2])
        + (F_y_RF - F_y_LF) * 0.5 * T_f * jnp.sin(x[2])
        + (F_x_LF - F_x_RF) * 0.5 * T_f * jnp.cos(x[2])
        + (F_x_LR - F_x_RR) * 0.5 * T_r
        - (F_y_LR + F_y_RR) * lr
    )

    sumY_s = (F_RAF + F_RAR) * jnp.cos(x[6]) + (F_SLF + F_SLR + F_SRF + F_SRR) * jnp.sin(
        x[6]
    )

    sumL = (
        0.5 * F_SLF * T_f
        + 0.5 * F_SLR * T_r
        - 0.5 * F_SRF * T_f
        - 0.5 * F_SRR * T_r
        - F_RAF
        / jnp.cos(x[6])
        * (
            h_s
            - x[11]
            - R_w
            + x[16]
            - (h_raf - R_w) * jnp.cos(x[13])
        )
        - F_RAR
        / jnp.cos(x[6])
        * (
            h_s
            - x[11]
            - R_w
            + x[21]
            - (h_rar - R_w) * jnp.cos(x[18])
        )
    )

    sumZ_s = (F_SLF + F_SLR + F_SRF + F_SRR) * jnp.cos(x[6]) - (F_RAF + F_RAR) * jnp.sin(
        x[6]
    )

    sumM_s = (
        lf * (F_SLF + F_SRF)
        - lr * (F_SLR + F_SRR)
        + (
            (F_x_LF + F_x_RF) * jnp.cos(x[2])
            - (F_y_LF + F_y_RF) * jnp.sin(x[2])
            + F_x_LR
            + F_x_RR
        )
        * (h_s - x[11])
    )

    # auxiliary variables unsprung mass
    sumL_uf = (
        0.5 * F_SRF * T_f
        - 0.5 * F_SLF * T_f
        - F_RAF * (h_raf - R_w)
        + F_z_LF
        * (
            R_w * jnp.sin(x[13])
            + 0.5 * T_f * jnp.cos(x[13])
            - K_lt * F_y_LF
        )
        - F_z_RF
        * (
            -R_w * jnp.sin(x[13])
            + 0.5 * T_f * jnp.cos(x[13])
            + K_lt * F_y_RF
        )
        - ((F_y_LF + F_y_RF) * jnp.cos(x[2]) + (F_x_LF + F_x_RF) * jnp.sin(x[2]))
        * (R_w - x[16])
    )

    sumL_ur = (
        0.5 * F_SRR * T_r
        - 0.5 * F_SLR * T_r
        - F_RAR * (h_rar - R_w)
        + F_z_LR
        * (
            R_w * jnp.sin(x[18])
            + 0.5 * T_r * jnp.cos(x[18])
            - K_lt * F_y_LR
        )
        - F_z_RR
        * (
            -R_w * jnp.sin(x[18])
            + 0.5 * T_r * jnp.cos(x[18])
            + K_lt * F_y_RR
        )
        - (F_y_LR + F_y_RR) * (R_w - x[21])
    )

    sumZ_uf = F_z_LF + F_z_RF + F_RAF * jnp.sin(x[6]) - (F_SLF + F_SRF) * jnp.cos(x[6])

    sumZ_ur = F_z_LR + F_z_RR + F_RAR * jnp.sin(x[6]) - (F_SLR + F_SRR) * jnp.cos(x[6])

    sumY_uf = (
        (F_y_LF + F_y_RF) * jnp.cos(x[2])
        + (F_x_LF + F_x_RF) * jnp.sin(x[2])
        - F_RAF * jnp.cos(x[6])
        - (F_SLF + F_SRF) * jnp.sin(x[6])
    )

    sumY_ur = (F_y_LR + F_y_RR) - F_RAR * jnp.cos(x[6]) - (F_SLR + F_SRR) * jnp.sin(x[6])

    # dynamics common with single-track model
    f = [0.0] * 29
    # switch to kinematic model for small velocities
    f[0] = jnp.cos(beta + x[4]) * vel
    f[1] = jnp.sin(beta + x[4]) * vel
    f[2] = u[0]
    f[3] = 1 / m * sumX + x[5] * x[10]
    f[4] = x[5]
    f[5] = (
        1
        / (I_z - (I_xz_s) ** 2 / I_Phi_s)
        * (sumN + I_xz_s / I_Phi_s * sumL)
    )

    # remaining sprung mass dynamics
    f[6] = x[7]
    f[7] = (
        1
        / (I_Phi_s - (I_xz_s) ** 2 / I_z)
        * (I_xz_s / I_z * sumN + sumL)
    )
    f[8] = x[9]
    f[9] = 1 / I_y_s * sumM_s
    f[10] = 1 / m_s * sumY_s - x[5] * x[3]
    f[11] = x[12]
    f[12] = g - 1 / m_s * sumZ_s

    # unsprung mass dynamics (front)
    f[13] = x[14]
    f[14] = 1 / I_uf * sumL_uf
    f[15] = 1 / m_uf * sumY_uf - x[5] * x[3]
    f[16] = x[17]
    f[17] = g - 1 / m_uf * sumZ_uf

    # unsprung mass dynamics (rear)
    f[18] = x[19]
    f[19] = 1 / I_ur * sumL_ur
    f[20] = 1 / m_ur * sumY_ur - x[5] * x[3]
    f[21] = x[22]
    f[22] = g - 1 / m_ur * sumZ_ur

    # convert acceleration input to brake and engine torque
    T_B = 0.0
    T_E = 0.0

    # wheel dynamics  (T  new parameter for torque splitting)
    f[23] = (
        1
        / I_y_w
        * (
            -R_w * F_x_LF
            + 0.5 * T_sb * T_B
            + 0.5 * T_se * T_E
        )
    )
    f[24] = (
        1
        / I_y_w
        * (
            -R_w * F_x_RF
            + 0.5 * T_sb * T_B
            + 0.5 * T_se * T_E
        )
    )
    f[25] = (
        1
        / I_y_w
        * (
            -R_w * F_x_LR
            + 0.5 * (1 - T_sb) * T_B
            + 0.5 * (1 - T_se) * T_E
        )
    )
    f[26] = (
        1
        / I_y_w
        * (
            -R_w * F_x_RR
            + 0.5 * (1 - T_sb) * T_B
            + 0.5 * (1 - T_se) * T_E
        )
    )

    # negative wheel spin forbidden
    for iState in range(23, 27):
        f[iState] = jnp.where(x[iState] < 0.0, 0.0, f[iState])

    # compliant joint equations
    f[27] = dot_delta_y_f
    f[28] = dot_delta_y_r

    return jnp.stack(f)
