/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenthfiala_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {11, 1, 1};

static const casadi_real casadi_zeros[9] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* f1tenthfiala_expl_ode_fun:(i0[9],i1[2],i2[11])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+23, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real *w24=w+36;
  const casadi_real *cs, *wr00;
  /* #0: @0 = input[0][0] */
  wr00 = arg[0] ? arg[0] : casadi_zeros;
  /* #1: @1 = @0[3] */
  w01 = wr00[3];
  /* #2: @2 = @0[2] */
  w02 = wr00[2];
  /* #3: @3 = cos(@2) */
  w03 = cos( w02 );
  /* #4: @4 = (@1*@3) */
  w04  = (w01*w03);
  /* #5: @5 = @0[4] */
  w05 = wr00[4];
  /* #6: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #7: @6 = (@5*@2) */
  w06  = (w05*w02);
  /* #8: @4 = (@4-@6) */
  w04 -= w06;
  /* #9: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #10: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #11: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #12: @2 = (@2+@3) */
  w02 += w03;
  /* #13: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #14: @2 = @0[5] */
  w02 = wr00[5];
  /* #15: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #16: @3 = 0.01 */
  w03 = 1.0000000000000000e-02;
  /* #17: @4 = 0.17145 */
  w04 = 1.7144999999999999e-01;
  /* #18: @6 = (@4*@2) */
  w06  = (w04*w02);
  /* #19: @6 = (@6-@5) */
  w06 -= w05;
  /* #20: @7 = 0.1 */
  w07 = 1.0000000000000001e-01;
  /* #21: @8 = sq(@1) */
  w08 = casadi_sq( w01 );
  /* #22: @8 = (@7+@8) */
  w08  = (w07+w08);
  /* #23: @8 = sqrt(@8) */
  w08 = sqrt( w08 );
  /* #24: @6 = atan2(@6,@8) */
  w06  = atan2(w06,w08);
  /* #25: @6 = tan(@6) */
  w06 = tan( w06 );
  /* #26: @9 = sq(@6) */
  w09 = casadi_sq( w06 );
  /* #27: @10 = 0.051 */
  w10 = 5.0999999999999997e-02;
  /* #28: @11 = @0[6] */
  w11 = wr00[6];
  /* #29: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #30: @12 = (@11-@1) */
  w12  = (w11-w01);
  /* #31: @12 = (@12/@8) */
  w12 /= w08;
  /* #32: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #33: @9 = (@9+@13) */
  w09 += w13;
  /* #34: @9 = (@3+@9) */
  w09  = (w03+w09);
  /* #35: @9 = sqrt(@9) */
  w09 = sqrt( w09 );
  /* #36: @13 = 3 */
  w13 = 3.;
  /* #37: @14 = 21.6952 */
  w14 = 2.1695192307692306e+01;
  /* #38: @15 = input[2][0] */
  casadi_copy(arg[2], 5, w15);
  /* #39: @16 = @15[3] */
  for (rr=(&w16), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #40: @16 = (@14*@16) */
  w16  = (w14*w16);
  /* #41: @17 = (@13*@16) */
  w17  = (w13*w16);
  /* #42: @18 = @15[1] */
  for (rr=(&w18), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #43: @19 = (@17/@18) */
  w19  = (w17/w18);
  /* #44: @19 = (@9<@19) */
  w19  = (w09<w19);
  /* #45: @18 = (@18*@9) */
  w18 *= w09;
  /* #46: @20 = sq(@18) */
  w20 = casadi_sq( w18 );
  /* #47: @20 = (@20/@17) */
  w20 /= w17;
  /* #48: @20 = (@18-@20) */
  w20  = (w18-w20);
  /* #49: @18 = pow(@18,@13) */
  w18  = pow(w18,w13);
  /* #50: @17 = 27 */
  w17 = 27.;
  /* #51: @21 = sq(@16) */
  w21 = casadi_sq( w16 );
  /* #52: @21 = (@17*@21) */
  w21  = (w17*w21);
  /* #53: @18 = (@18/@21) */
  w18 /= w21;
  /* #54: @20 = (@20+@18) */
  w20 += w18;
  /* #55: @20 = (@19?@20:0) */
  w20  = (w19?w20:0);
  /* #56: @19 = (!@19) */
  w19 = (! w19 );
  /* #57: @19 = (@19?@16:0) */
  w19  = (w19?w16:0);
  /* #58: @20 = (@20+@19) */
  w20 += w19;
  /* #59: @12 = (@20*@12) */
  w12  = (w20*w12);
  /* #60: @12 = (@12/@9) */
  w12 /= w09;
  /* #61: @19 = @15[4] */
  for (rr=(&w19), cs=w15+4; cs!=w15+5; cs+=1) *rr++ = *cs;
  /* #62: @14 = (@14*@19) */
  w14 *= w19;
  /* #63: @19 = (2.*@1) */
  w19 = (2.* w01 );
  /* #64: @19 = tanh(@19) */
  w19 = tanh( w19 );
  /* #65: @14 = (@14*@19) */
  w14 *= w19;
  /* #66: @12 = (@12-@14) */
  w12 -= w14;
  /* #67: @14 = @0[8] */
  w14 = wr00[8];
  /* #68: @19 = 0.15875 */
  w19 = 1.5875000000000000e-01;
  /* #69: @16 = (@19*@2) */
  w16  = (w19*w02);
  /* #70: @18 = (@16+@5) */
  w18  = (w16+w05);
  /* #71: @18 = atan2(@18,@8) */
  w18  = atan2(w18,w08);
  /* #72: @18 = (@14-@18) */
  w18  = (w14-w18);
  /* #73: @18 = tan(@18) */
  w18 = tan( w18 );
  /* #74: @8 = sq(@18) */
  w08 = casadi_sq( w18 );
  /* #75: @21 = cos(@14) */
  w21 = cos( w14 );
  /* #76: @22 = (@1*@21) */
  w22  = (w01*w21);
  /* #77: @16 = (@5+@16) */
  w16  = (w05+w16);
  /* #78: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #79: @16 = (@16*@14) */
  w16 *= w14;
  /* #80: @22 = (@22+@16) */
  w22 += w16;
  /* #81: @11 = (@11-@22) */
  w11 -= w22;
  /* #82: @22 = sq(@22) */
  w22 = casadi_sq( w22 );
  /* #83: @7 = (@7+@22) */
  w07 += w22;
  /* #84: @7 = sqrt(@7) */
  w07 = sqrt( w07 );
  /* #85: @11 = (@11/@7) */
  w11 /= w07;
  /* #86: @7 = sq(@11) */
  w07 = casadi_sq( w11 );
  /* #87: @8 = (@8+@7) */
  w08 += w07;
  /* #88: @3 = (@3+@8) */
  w03 += w08;
  /* #89: @3 = sqrt(@3) */
  w03 = sqrt( w03 );
  /* #90: @8 = 23.4308 */
  w08 = 2.3430807692307692e+01;
  /* #91: @7 = @15[2] */
  for (rr=(&w07), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #92: @8 = (@8*@7) */
  w08 *= w07;
  /* #93: @7 = (@13*@8) */
  w07  = (w13*w08);
  /* #94: @22 = @15[0] */
  for (rr=(&w22), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #95: @16 = (@7/@22) */
  w16  = (w07/w22);
  /* #96: @16 = (@3<@16) */
  w16  = (w03<w16);
  /* #97: @22 = (@22*@3) */
  w22 *= w03;
  /* #98: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #99: @23 = (@23/@7) */
  w23 /= w07;
  /* #100: @23 = (@22-@23) */
  w23  = (w22-w23);
  /* #101: @22 = pow(@22,@13) */
  w22  = pow(w22,w13);
  /* #102: @13 = sq(@8) */
  w13 = casadi_sq( w08 );
  /* #103: @17 = (@17*@13) */
  w17 *= w13;
  /* #104: @22 = (@22/@17) */
  w22 /= w17;
  /* #105: @23 = (@23+@22) */
  w23 += w22;
  /* #106: @23 = (@16?@23:0) */
  w23  = (w16?w23:0);
  /* #107: @16 = (!@16) */
  w16 = (! w16 );
  /* #108: @16 = (@16?@8:0) */
  w16  = (w16?w08:0);
  /* #109: @23 = (@23+@16) */
  w23 += w16;
  /* #110: @11 = (@23*@11) */
  w11  = (w23*w11);
  /* #111: @11 = (@11/@3) */
  w11 /= w03;
  /* #112: @16 = (@11*@21) */
  w16  = (w11*w21);
  /* #113: @16 = (@12+@16) */
  w16  = (w12+w16);
  /* #114: @23 = (@23*@18) */
  w23 *= w18;
  /* #115: @23 = (@23/@3) */
  w23 /= w03;
  /* #116: @3 = (@23*@14) */
  w03  = (w23*w14);
  /* #117: @16 = (@16-@3) */
  w16 -= w03;
  /* #118: @3 = 4.6 */
  w03 = 4.5999999999999996e+00;
  /* #119: @16 = (@16/@3) */
  w16 /= w03;
  /* #120: @5 = (@5*@2) */
  w05 *= w02;
  /* #121: @16 = (@16+@5) */
  w16 += w05;
  /* #122: output[0][3] = @16 */
  if (res[0]) res[0][3] = w16;
  /* #123: @20 = (@20*@6) */
  w20 *= w06;
  /* #124: @20 = (@20/@9) */
  w20 /= w09;
  /* #125: @23 = (@23*@21) */
  w23 *= w21;
  /* #126: @21 = (@20+@23) */
  w21  = (w20+w23);
  /* #127: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #128: @21 = (@21+@14) */
  w21 += w14;
  /* #129: @21 = (@21/@3) */
  w21 /= w03;
  /* #130: @1 = (@1*@2) */
  w01 *= w02;
  /* #131: @21 = (@21-@1) */
  w21 -= w01;
  /* #132: output[0][4] = @21 */
  if (res[0]) res[0][4] = w21;
  /* #133: @23 = (@23+@14) */
  w23 += w14;
  /* #134: @19 = (@19*@23) */
  w19 *= w23;
  /* #135: @4 = (@4*@20) */
  w04 *= w20;
  /* #136: @19 = (@19-@4) */
  w19 -= w04;
  /* #137: @4 = 0.04712 */
  w04 = 4.7120000000000002e-02;
  /* #138: @19 = (@19/@4) */
  w19 /= w04;
  /* #139: output[0][5] = @19 */
  if (res[0]) res[0][5] = w19;
  /* #140: @19 = 0.025744 */
  w19 = 2.5743960000000000e-02;
  /* #141: @4 = @0[7] */
  w04 = wr00[7];
  /* #142: @19 = (@19*@4) */
  w19 *= w04;
  /* #143: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #144: @19 = (@19-@12) */
  w19 -= w12;
  /* #145: @10 = (@10*@11) */
  w10 *= w11;
  /* #146: @19 = (@19-@10) */
  w19 -= w10;
  /* #147: @10 = 0.00143406 */
  w10 = 1.4340581999999998e-03;
  /* #148: @19 = (@19/@10) */
  w19 /= w10;
  /* #149: output[0][6] = @19 */
  if (res[0]) res[0][6] = w19;
  /* #150: @24 = input[1][0] */
  casadi_copy(arg[1], 2, w24);
  /* #151: @19 = @24[0] */
  for (rr=(&w19), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #152: output[0][7] = @19 */
  if (res[0]) res[0][7] = w19;
  /* #153: @19 = @24[1] */
  for (rr=(&w19), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #154: output[0][8] = @19 */
  if (res[0]) res[0][8] = w19;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenthfiala_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenthfiala_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenthfiala_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenthfiala_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenthfiala_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 38;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenthfiala_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 38*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
